---
analyze_event_task:
  description: >
    Analyze foreign policy event: {input_event_description}.
    Consider the provided Aggression Level: {aggression_level} and Domain Emphasis: {domain_emphasis}.
    Detail: nature of the event, direct/indirect impact on Chinese core interests,
    initiating entity's likely objectives/red lines, potential escalatory pathways,
    key sensitivities for China. Explicitly assess how this event might be
    interpreted through the lens of China's historical narratives, its current
    ideological discourse (e.g., National Rejuvenation, struggle against hegemonism),
    and its potential ramifications for domestic public opinion and Party legitimacy.
  expected_output: |
    Format your response as follows:

    core_event_details: < 70 words
    risk_score: 1-5
    top_red_lines:
      - "..."
      - "..."
  agent: ForeignPolicyEventAnalystAgent

assess_economic_tech_impact_task:
  description: >
    Using {context.analyze_event_task.core_event_details}, evaluate economic &
    tech impacts. Ignore ideological angles.
  expected_output: |
    Format your response as follows:

    vulnerabilities: [ "...", "..." ]
    leverage_points:  [ "...", "..." ]
  context:
    - analyze_event_task
  agent: EconomicAndTechImpactAnalystAgent

historical_context_task:
  description: >
    Based on the event analysis and the CCP's historical narratives,
    provide a concise overview of how this event aligns with or diverges from
    China's historical experiences and ideological discourse. Highlight
    key historical events, ideological themes, and narratives that can be
    leveraged to frame the current situation in a manner that resonates with
    both domestic and international audiences. Drawing upon Chinese history and
    established strategic culture, provide an analysis of how past events and ingrained strategic thinking
    might influence the current leadership's interpretation of and response to the external action.
    1. Are there significant historical parallels (e.g., "Century of Humiliation",
    past dealings with specific nations involved) that might shape perceptions?
    2. Do any long-standing strategic principles (e.g., "keeping a low profile",
    "active defense," views on sovereignty) appear particularly relevant?
    3. How might cultural factors influence the preferred style of response
    (e.g., direct confrontation vs. indirect pressure, importance of "face")?
    4. What historical lessons (successful or unsuccessful) might be drawn upon
    by decision-makers in this context?
    Your output MUST be a report detailing relevant historical precedents and
    strategic cultural considerations pertinent to the external action.
  expected_output: >
    An analytical report connecting the current external action to relevant
    Chinese historical precedents, strategic culture, and potential lessons influencing decision-making
  agent: HistoricalPrecedentAnalyst
  context:
    - analyze_event_task

internal_impact_narrative_task:
  description: >
    Considering the external action and preceding analyses (ideological, economic, security),
    assess the potential impact on domestic public sentiment (as perceived by state monitors) and social stability in China.
    1. How might this action be interpreted by different segments of the Chinese populace if widely known?
    2. What are the risks of this action fueling undesirable nationalist sentiment or social unrest?
    3. How can state media and information channels effectively frame this action and China's response to maintain domestic cohesion and support for the Party?
    4. Are there specific internal narratives that should be emphasized or countered?
    Your output MUST be a concise report on potential domestic impacts and recommended narrative management strategies.
  expected_output: >
    A report on potential domestic public opinion impacts, social stability risks,
    and recommended internal narrative management strategies.
  agent: DomesticSentimentStabilityAnalyst
  context:
    - analyze_event_task
    - assess_economic_tech_impact_task
    - historical_context_task

develop_active_strategic_postures_task:
  description: >
    Synthesize the core event facts from
    {context.analyze_event_task.core_event_details}
    together with the economic/tech impact assessment in
    {context.assess_economic_tech_impact_task.vulnerabilities}
    + {context.assess_economic_tech_impact_task.leverage_points}.
    Integrate historical precedents from {context.historical_context_task.output}
    and domestic sentiment considerations from {context.internal_impact_narrative_task.output}.
    Through the lens of the "Holistic National Security Concept",
    define **2-3 active strategic postures** for China and justify each
    (<= 800 words total).  Reference relevant guidance in PRC_GrayZone_Planner.md.
  expected_output: >
    Concise document (<= 800 words) outlining 2-3 distinct active strategic
    postures with justifications.
  context:
    - analyze_event_task
    - assess_economic_tech_impact_task
    - historical_context_task
    - internal_impact_narrative_task
  agent: CCPStrategicPolicyAdvisor

assess_signaling_and_recommend_strategic_path_task:
  description: >
    Based on the strategic postures from {context.develop_active_strategic_postures_task.output}
    and the original event facts in {context.analyze_event_task.core_event_details},
    present THREE distinct strategic response approaches for human selection:

    1. **Active Posture**: Immediate, assertive response with concrete actions (military, economic, diplomatic)
    2. **Strategic Ambiguity**: Maintain calculated uncertainty about China's intentions and responses
    3. **Calibrated Delay**: Measured postponement of response while gathering intelligence and preparing options

    For each approach, analyze signaling implications, escalation risks, and likely outcomes.
    Present a clear recommendation but require human confirmation of the chosen path.
  expected_output: >
    ***STRATEGIC RESPONSE PATH SELECTION***

    **EVENT CONTEXT:**
    {Brief summary of the triggering event and key stakes}

    **THREE RESPONSE APPROACHES:**

    **OPTION 1: ACTIVE POSTURE**
    - Description: Immediate assertive response demonstrating China's resolve
    - Concrete Actions Would Include: [2-3 specific examples from postures analysis]
    - Signaling Effect: [Clear, strong deterrent message]
    - Escalation Risk: [High/Medium/Low with justification]
    - Timeline: Immediate (24-72 hours)

    **OPTION 2: STRATEGIC AMBIGUITY**
    - Description: Maintain uncertainty about China's response while preserving options
    - Concrete Actions Would Include: [Vague statements, behind-scenes preparation]
    - Signaling Effect: [Keeps adversaries guessing, maintains flexibility]
    - Escalation Risk: [High/Medium/Low with justification]
    - Timeline: Extended (1-2 weeks)

    **OPTION 3: CALIBRATED DELAY**
    - Description: Measured postponement while gathering intelligence and preparing comprehensive response
    - Concrete Actions Would Include: [Information gathering, consultations, preparation]
    - Signaling Effect: [Deliberate, measured response suggesting serious consideration]
    - Escalation Risk: [High/Medium/Low with justification]
    - Timeline: Extended (2-4 weeks)

    **AGENT RECOMMENDATION:** [Option X]
    **Justification:** [2-3 sentences explaining why this option best fits the situation]

    **HUMAN DECISION REQUIRED:**
    Please select ONE of the following:
    A) Active Posture
    B) Strategic Ambiguity
    C) Calibrated Delay

    Your Choice: [Human to fill: A, B, or C]
  human_input: true
  context:
    - analyze_event_task
    - develop_active_strategic_postures_task
  agent: StrategicSignalingAssessmentAgent

generate_active_pla_options_task:
  description: >
    Based on the human-selected strategic path from {context.assess_signaling_and_recommend_strategic_path_task.output}:

    - IF "Active Posture" was selected: Generate 2-3 specific PLA military options that align with the chosen approach
    - IF "Strategic Ambiguity" was selected: Generate 1-2 ambiguous military preparations that don't reveal intentions
    - IF "Calibrated Delay" was selected: Generate intelligence-gathering and preparation activities only

    Reference {context.analyze_event_task.top_red_lines} to ensure options are appropriately calibrated.
  expected_output: |
    Based on whether selected_path is "[Active Posture/Strategic Ambiguity/Calibrated Delay]"
    format your response as follows:

    military_options:
      - name: "[Option name based on selected path]"
        summary: "[Detailed summary]"
        path_alignment: "[How this aligns with chosen strategic approach]"
  context:
    - analyze_event_task
    - assess_signaling_and_recommend_strategic_path_task
  agent: PLAOptionsStrategistAgent

ideological_perception_task:
  description: >
    Review the human-selected strategic path from {context.assess_signaling_and_recommend_strategic_path_task.output}
    and analyze ideological alignment:

    - Extract pivotal ideological themes and doctrinal cues relevant to the chosen path
    - Explain how the selected approach aligns with Party ideology and Xi Jinping Thought
    - Flag any potentially non-compliant language based on the chosen strategy
    - Suggest high-ground ideological frames for official messaging that match the strategic approach

    Tailor ideological framing to support the selected path (active/ambiguous/delayed).
  expected_output: |
    Based on whether selected_path is selected_path is "[Active Posture/Strategic Ambiguity/Calibrated Delay]"
    format your response as follows:

    memo: |
      "Concise (<=300 words) Ideological Compliance & Leverage Memo tailored to chosen path"
    key_frames:
      - "Ideological frame 1 supporting selected strategy"
      - "Ideological frame 2 supporting selected strategy"
    compliance_assessment: "Analysis of how chosen path aligns with Party doctrine"
  context:
    - assess_signaling_and_recommend_strategic_path_task
  agent: CCPIdeologicalAnalyst

develop_active_diplomatic_strategy_task:
  description: >
    Based on the human-selected strategic path from {context.assess_signaling_and_recommend_strategic_path_task.output},
    craft the MFA strategy with path-specific approaches:

    - IF "Active Posture" was selected: Draft strong, definitive diplomatic statements with clear positions
    - IF "Strategic Ambiguity" was selected: Create carefully worded statements that preserve flexibility
    - IF "Calibrated Delay" was selected: Focus on procedural statements about consultations
  expected_output: |
    Based on whether selected_path is selected_path is: "[Active Posture/Strategic Ambiguity/Calibrated Delay]"
    format your response as follows:

    keystone_statement: |
      "Draft MFA line (<=200 words) tailored to chosen strategic path"
    engagement_plan:
      - "Primary diplomatic channels and messaging"
    path_rationale: "How diplomatic approach aligns with chosen strategy"
  context:
    - analyze_event_task
    - assess_signaling_and_recommend_strategic_path_task
    - generate_active_pla_options_task
    - ideological_perception_task
    - historical_context_task
    - internal_impact_narrative_task
  agent: MFADiplomaticStrategistAgent

develop_strategic_communication_plan_task:
  description: >
    Using the consolidated context from {context.curate_context_digest_task.digest},
    craft a Strategic Communication Plan that adapts messaging to the chosen strategic path:

    - IF "Active Posture": Emphasize strength, resolve, and justified defensive actions
    - IF "Strategic Ambiguity": Focus on principled positions while avoiding specific commitments
    - IF "Calibrated Delay": Highlight deliberation, consultation, and measured consideration
  expected_output: >
    **STRATEGIC COMMUNICATION PLAN**

    **Selected Path:** [Active Posture/Strategic Ambiguity/Calibrated Delay]

    **Domestic Narratives:**
    - Core message for Chinese audiences

    **International Messaging:**
    - Primary message for global audiences

    **Media Guidance:**
    - State media talking points

    **Social Media Strategy:**
    - Unofficial amplification themes

    **Counter-Narrative Measures:**
    - Anticipated opposing narratives
  agent: StrategicNarrativeAndInfluenceAgent
  context:
    - curate_context_digest_task

curate_context_digest_task:
  description: >
    Collate the following into a single digest <=600 tokens:
      - {context.analyze_event_task.core_event_details}
      - {context.assess_signaling_and_recommend_strategic_path_task.output}
      - {context.generate_active_pla_options_task.military_options}
      - {context.develop_active_diplomatic_strategy_task.keystone_statement}
      - {context.ideological_perception_task.key_frames}
      - {context.historical_context_task.output}
      - {context.internal_impact_narrative_task.output}
  expected_output: |
    Format your response as follows:

    digest: >-
      core_event_details: "Summary of event details (approx. 70 words)."
      risk_score: "Calculated risk score (1-5)."
      top_red_lines:
        - "Red line 1"
        - "Red line 2"
      chosen_strategic_path: "The strategic path chosen by human input (e.g., Active Posture: Posture A, Strategic Ambiguity, Calibrated Delay)."
      # PLA options should only be populated if 'Active Posture' was chosen. Otherwise, 'Not Applicable' or empty list.
      pla_options:
        - name: "Military Option 1 Name (e.g., Show-of-Force Patrol)"
          summary: "Summary of military option 1."
        - name: "Military Option 2 Name"
          summary: "Summary of military option 2."
      keystone_diplomatic_statement: "Full text of the keystone MFA diplomatic statement (approx. 200 words)."
      ideological_key_frames:
        - "Key ideological frame 1."
        - "Key ideological frame 2."
      historical_context_summary: "Concise summary of relevant historical precedents and strategic cultural considerations."
      internal_impact_summary: "Concise summary of potential domestic public opinion impacts, social stability risks, and narrative strategies."
  agent: ContextCuratorAgent
  context:
    - analyze_event_task
    - assess_signaling_and_recommend_strategic_path_task
    - generate_active_pla_options_task
    - develop_active_diplomatic_strategy_task
    - ideological_perception_task
    - historical_context_task
    - internal_impact_narrative_task

format_final_response_task:
  description: >
    Synthesize analyses into final public-facing response format, adhering to "XJP Instructions 1.md".

    **Path-Specific Output Requirements:**
    - IF "Active Posture": Include 2-3 concrete, decisive actions in past tense from PLA and diplomatic options
    - IF "Strategic Ambiguity": Include 1-2 measured, non-committal actions that preserve flexibility
    - IF "Calibrated Delay": Include procedural/consultative actions showing deliberate consideration

    Select most realistic, impactful actions based on chosen strategic path.
    Consult "PRC_GrayZone_Planner.md" and "XJP Instructions 1.md" for style and tone.

    **CRITICAL: Do NOT include reasoning, analysis, thinking process, or internal deliberations.
    Only provide the final formatted response as specified in the expected output.**
  expected_output: >
    **STRATEGIC PATH SELECTED:** [Active Posture/Strategic Ambiguity/Calibrated Delay]

    **China's Actions:**
    1. [Action 1, past tense, aligned with chosen path]
    2. [Action 2, past tense, if applicable]
    3. [Action 3, past tense, if applicable]

    **Official Statement:**
    [Key diplomatic statement from MFA strategy, adapted to chosen path]

    **Unofficial Social Media Post (Twitter):**
    [Max 280 characters reflecting chosen strategic approach, including good faith emphasis per XJP Instructions, with appropriate hashtags/emojis]
  agent: ResponseSynthesizerAgent
  context:
    - curate_context_digest_task
  output_file: output/final_response.md
