analyze_event_task:
  description: >
    Analyze foreign policy event: {input_event_description}.
    Consider the provided Aggression Level: {aggression_level} and Domain Emphasis: {domain_emphasis}.
    Detail: nature of the event, direct/indirect impact on Chinese core interests,
    initiating entity's likely objectives/red lines, potential escalatory pathways,
    key sensitivities for China. Explicitly assess how this event might be
    interpreted through the lens of China's historical narratives, its current
    ideological discourse (e.g., National Rejuvenation, struggle against hegemonism),
    and its potential ramifications for domestic public opinion and Party legitimacy.
  expected_output: |
    core_event_details: < 70 words
    risk_score: 1‑5
    top_red_lines:
      - "…"
      - "…"
  agent: ForeignPolicyEventAnalystAgent

assess_economic_tech_impact_task:
  description: >
    Using {context.analyze_event_task.core_event_details}, evaluate economic &
    tech impacts. Ignore ideological angles.
  expected_output: |
    vulnerabilities: [ "…", "…" ]
    leverage_points:  [ "…", "…" ]
  context:
    - analyze_event_task
  agent: EconomicAndTechImpactAnalystAgent

historical_context_task:
  description: >
    Based on the event analysis and the CCP's historical narratives,
    provide a concise overview of how this event aligns with or diverges from
    China's historical experiences and ideological discourse. Highlight
    key historical events, ideological themes, and narratives that can be
    leveraged to frame the current situation in a manner that resonates with
    both domestic and international audiences. Drawing upon Chinese history and
    established strategic culture, provide an analysis of how past events and ingrained strategic thinking
    might influence the current leadership's interpretation of and response to the external action.
    1. Are there significant historical parallels (e.g., "Century of Humiliation",
    past dealings with specific nations involved) that might shape perceptions?
    2. Do any long-standing strategic principles (e.g., "keeping a low profile,"
    "active defense," views on sovereignty) appear particularly relevant?
    3. How might cultural factors influence the preferred style of response
    (e.g., direct confrontation vs. indirect pressure, importance of "face")?
    4. What historical lessons (successful or unsuccessful) might be drawn upon
    by decision-makers in this context?
    Your output MUST be a report detailing relevant historical precedents and
    strategic cultural considerations pertinent to the external action.
  expected_output: >
    An analytical report connecting the current external action to relevant
    Chinese historical precedents, strategic culture, and potential lessons influencing decision-making
  agent: HistoricalPrecedentAnalyst
  context:
    - analyze_event_task

internal_impact_narrative_task:
  description: >
    Considering the external action and preceding analyses (ideological, economic, security),
    assess the potential impact on domestic public sentiment (as perceived by state monitors) and social stability in China.
    1. How might this action be interpreted by different segments of the Chinese populace if widely known?
    2. What are the risks of this action fueling undesirable nationalist sentiment or social unrest?
    3. How can state media and information channels effectively frame this action and China's response to maintain domestic cohesion and support for the Party?
    4. Are there specific internal narratives that should be emphasized or countered?
    Your output MUST be a concise report on potential domestic impacts and recommended narrative management strategies.
  expected_output: >
    A report on potential domestic public opinion impacts, social stability risks,
    and recommended internal narrative management strategies.
  agent: DomesticSentimentStabilityAnalyst
  context:
    - analyze_event_task
    - assess_economic_tech_impact_task
    - historical_context_task

develop_active_strategic_postures_task:
  description: >
    Synthesise the core event facts from
    {context.analyze_event_task.core_event_details}
    together with the economic/tech impact assessment in
    {context.assess_economic_tech_impact_task.vulnerabilities}
    + {context.assess_economic_tech_impact_task.leverage_points}.
    Integrate historical precedents from {context.historical_context_task.output}
    and domestic sentiment considerations from {context.internal_impact_narrative_task.output}.
    Through the lens of the “Holistic National Security Concept”,
    define **2-3 active strategic postures** for China and justify each
    (≤ 800 words total).  Reference relevant guidance in PRC_GrayZone_Planner.md.
  expected_output: >
    Concise document (≤ 800 words) outlining 2-3 distinct active strategic
    postures with justifications.
  context:
    - analyze_event_task
    - assess_economic_tech_impact_task
    - historical_context_task
    - internal_impact_narrative_task
  agent: CCPStrategicPolicyAdvisor

assess_signaling_and_recommend_strategic_path_task:
  description: >
    Review the proposed active postures from
    {context.develop_active_strategic_postures_task.output} plus the
    original event facts in {context.analyze_event_task.core_event_details}.
    Assess signalling implications and escalation risks, then recommend ONE
    overarching path (‘Active Posture’, ‘Strategic Ambiguity’, or
    ‘Calibrated Delay’) with justification.  Ask the human user to confirm
    the choice before downstream tasks proceed.
        expected_output: >
          **Human Review Required**

          **Proposed Strategic Postures (from CCPStrategicPolicyAdvisor):**
          1. Posture A: [Details]
             - Justification: ...
          2. Posture B: [Details]
             - Justification: ...

          **Strategic Signaling Assessment Agent's Analysis:**
          - Signaling Implications of Posture A: ...
          - Escalatory Risks of Posture A: ...
          - Signaling Implications of Posture B: ...
          - Escalatory Risks of Posture B: ...
          - Analysis of 'Strategic Ambiguity' option: ...
          - Analysis of 'Calibrated Delay' option: ...

          **Strategic Signaling Assessment Agent's Recommendation:**
          Recommended Path: [Active Posture: <details> | Strategic Ambiguity | Calibrated Delay]
          Justification for Recommendation: ...

          **Your Decision is Required Below:**
          Chosen Strategic Path: [Human to fill: e.g., Active Posture: Posture A | Strategic Ambiguity | Calibrated Delay]
  human_input: True
  context:
    - analyze_event_task
    - develop_active_strategic_postures_task

generate_active_pla_options_task:
  description: >
    Based on {context.analyze_event_task.top_red_lines} produce ≤3 PLA options
    (one sentence each) that dovetail with the signalling path.
  expected_output: |
    military_options:
      - name: "Show‑of‑Force Patrol"
        summary: "…"
      - name: "Precision Drill …"
        summary: "…"
  context:
    - analyze_event_task
    - assess_signaling_and_recommend_strategic_path_task
  agent: PLAOptionsStrategistAgent

develop_active_diplomatic_strategy_task:
  description: >
    Using ONLY:
      – {context.analyze_event_task.core_event_details}
      – {context.assess_signaling_and_recommend_strategic_path_task.output}
      – {context.generate_active_pla_options_task.military_options}
      – {context.ideological_perception_task.key_frames}
      – {context.historical_context_task.output}
      – {context.internal_impact_narrative_task.output}
    craft the MFA strategy (see path‑conditional instructions).
  expected_output: |
    chosen_path: "Active Posture | Strategic Ambiguity | Calibrated Delay"
    keystone_statement: |
      "Draft MFA line ( ≤200 words ) …"
    engagement_plan: [ "actor ⇒ engagement mode", "…" ]
  context:
    - analyze_event_task
    - assess_signaling_and_recommend_strategic_path_task
    - generate_active_pla_options_task
    - ideological_perception_task
    - historical_context_task
    - internal_impact_narrative_task
  agent: MFADiplomaticStrategistAgent

ideological_perception_task:
  description: >
    Extract ONLY the ideological pivots in
    {context.assess_signaling_and_recommend_strategic_path_task.output}
    and produce a ≤300-word “Ideological Compliance & Leverage Memo”.
    Ignore all other upstream outputs.
  expected_output: |
    key_frames:
      - "…"
      - "…"
  context:
    - assess_signaling_and_recommend_strategic_path_task
  agent: CCPIdeologicalAnalyst


develop_strategic_communication_plan_task:
  description: >
    Use the consolidated bullet list in {context.curate_context_digest_task.digest}
    to craft a Strategic Communication Plan. This plan must specify-
    1. Core narratives for domestic consumption. 2. Key messages for international audiences
    (differentiating by target region/country if necessary). 3. Guidance for state media outlets.
    4. Themes for unofficial but aligned social media amplification. 5. Potential pre-emptive
    or reactive counter-narrative measures. Actively draw upon the 'Media and Public Perception'
    and 'Denial and Deception' sections of 'PRC_GrayZone_Planner.md'.
  expected_output: >
    A concise Strategic Communication Plan document.
  agent: StrategicNarrativeAndInfluenceAgent
  context:
    - curate_context_digest_task.digest
# instead of pulling seven separate blobs.

curate_context_digest_task:
  description: >
    Collate the following into a single digest ≤600 tokens:
      – {context.analyze_event_task.core_event_details}
      – {context.assess_signaling_and_recommend_strategic_path_task.output}
      – {context.generate_active_pla_options_task.military_options}
      – {context.develop_active_diplomatic_strategy_task.keystone_statement}
      – {context.ideological_perception_task.key_frames}
      – {context.historical_context_task.output}
      – {context.internal_impact_narrative_task.output}
  expected_output: |
    digest: |
      "… consolidated bullet list …"
  context:
    - analyze_event_task
    - assess_signaling_and_recommend_strategic_path_task
    - generate_active_pla_options_task
    - develop_active_diplomatic_strategy_task
    - ideological_perception_task
    - historical_context_task
    - internal_impact_narrative_task
  agent: ContextCuratorAgent


format_final_response_task:
  description: >
    Synthesize the analyses and decisions from previous steps into the final
    public-facing response format, strictly adhering to "XJP Instructions 1.md".
    Consider the chosen strategic path from '{context.assess_signaling_and_recommend_strategic_path_task.output}'.
    If the path is 'Active Posture', draw concrete actions primarily from the PLA options
    in '{context.generate_active_pla_options_task.output}' and key diplomatic actions
    from '{context.develop_active_diplomatic_strategy_task.output}'.
    Select 2-3 of the most realistic, impactful, and concrete actions, ensuring they are in past tense.
    Consult "PRC_GrayZone_Planner.md" and "XJP Instructions 1.md" for style, tone, and content.
    The "China's Actions" should be distinct, non-overlapping, and represent tangible steps taken.
    Do NOT include any of the thinking, logic, or reasoning behind the response.
  expected_output: >
    A string containing the final response formatted exactly as follows:
    China's Actions:
    1. [Action 1, past tense]
    2. [Action 2, past tense, if applicable]
    3. [Action 3, past tense, if applicable]

    For the "Unofficial Social Media Post (Twitter)":
        - Max 280 characters.
        - Reflect overall situation, sentiment, and official messaging.
        - Incorporate key diplomatic messages (e.g., calls for dialogue, statements made) from
          '{context.develop_active_diplomatic_strategy_task.output}' and narrative themes from
          '{context.develop_strategic_communication_plan_task.output}'.
        - Include "good faith emphasis" as per "XJP Instructions 1.md".
        - Use informal language, relevant hashtags/emojis.
        - Adhere to common Chinese social media narrative styles.
  agent: ResponseSynthesizerAgent
  context:
    - curate_context_digest_task.digest
# instead of pulling seven separate blobs.
  output_file: output/final_response.md
