analyze_event_task:
  description: >
    Analyze foreign policy event: {input_event_description}.
    Consider the provided Aggression Level: {aggression_level} and Domain Emphasis: {domain_emphasis}.
    Detail: nature of the event, direct/indirect impact on Chinese core interests,
    initiating entity's likely objectives/red lines, potential escalatory pathways,
    key sensitivities for China. Explicitly assess how this event might be
    interpreted through the lens of China's historical narratives, its current
    ideological discourse (e.g., National Rejuvenation, struggle against hegemonism),
    and its potential ramifications for domestic public opinion and Party legitimacy.
  Output: Concise analytical brief (max 700 words).
  expected_output: >
    Concise analytical brief covering event details, impact on core interests,
    initiator's objectives/red lines, escalation pathways, key sensitivities,
    and an analysis of the event's ideological and domestic narrative implications for China.
  agent: ForeignPolicyEventAnalystAgent

assess_economic_tech_impact_task:
  description: >
    Based on event analysis, analyze economic and technological
    impacts of the event on China.
    Consider supply chains, key industries, financial stability,
    technological self-sufficiency goals, and ongoing competition.
    Propose potential vulnerabilities and leverage points for China.
    Output: Concise impact assessment (max 500 words).
  expected_output: >
    Concise impact assessment covering economic and technological aspects
    with vulnerabilities and leverage points.
  agent: EconomicAndTechImpactAnalystAgent
  context:
    - analyze_event_task

historical_context_task:
  description: >
    Based on the event analysis and the CCP's historical narratives,
    provide a concise overview of how this event aligns with or diverges from
    China's historical experiences and ideological discourse. Highlight
    key historical events, ideological themes, and narratives that can be
    leveraged to frame the current situation in a manner that resonates with
    both domestic and international audiences. Drawing upon Chinese history and
    established strategic culture, provide an analysis of how past events and ingrained strategic thinking
    might influence the current leadership's interpretation of and response to the external action.
    1. Are there significant historical parallels (e.g., "Century of Humiliation",
    past dealings with specific nations involved) that might shape perceptions?
    2. Do any long-standing strategic principles (e.g., "keeping a low profile,"
    "active defense," views on sovereignty) appear particularly relevant?
    3. How might cultural factors influence the preferred style of response
    (e.g., direct confrontation vs. indirect pressure, importance of "face")?
    4. What historical lessons (successful or unsuccessful) might be drawn upon
    by decision-makers in this context?
    Your output MUST be a report detailing relevant historical precedents and
    strategic cultural considerations pertinent to the external action.
  expected_output: >
    An analytical report connecting the current external action to relevant
    Chinese historical precedents, strategic culture, and potential lessons influencing decision-making
  agent: HistoricalPrecedentAnalyst
  context:
    - analyze_event_task

internal_impact_narrative_task:
  description: >
    Considering the external action and preceding analyses (ideological, economic, security),
    assess the potential impact on domestic public sentiment (as perceived by state monitors) and social stability in China.
    1. How might this action be interpreted by different segments of the Chinese populace if widely known?
    2. What are the risks of this action fueling undesirable nationalist sentiment or social unrest?
    3. How can state media and information channels effectively frame this action and China's response to maintain domestic cohesion and support for the Party?
    4. Are there specific internal narratives that should be emphasized or countered?
    Your output MUST be a concise report on potential domestic impacts and recommended narrative management strategies.
  expected_output: >
    A report on potential domestic public opinion impacts, social stability risks,
    and recommended internal narrative management strategies.
  agent: DomesticSentimentStabilityAnalyst
  context:
    - analyze_event_task
    - assess_economic_tech_impact_task
    - historical_context_task

develop_active_strategic_postures_task:
  description: >
    Based on the comprehensive initial analysis from '{context.analyze_event_task.output}'
    and the economic/tech impact assessment from '{context.assess_economic_tech_impact_task.output}',
    synthesize these findings through the lens of the 'Holistic National Security Concept'.
    Then, define 2-3 plausible active strategic response postures for China.
    Justify each by CCP priorities, risk tolerance across all security domains (political,
    economic, military, cultural, social etc.), and desired end-states.
  Explicitly reference and use insights from the 'PRC_GrayZone_Planner.md'.
  Output: Concise document (max 800 words total) of active postures with justifications.
  expected_output: >
    Document outlining 2-3 distinct active strategic postures with
    justifications.
  agent: CCPStrategicPolicyAdvisor
  context:
    - analyze_event_task
    - assess_economic_tech_impact_task
    - internal_impact_narrative_task
    - historical_context_task

assess_signaling_and_recommend_strategic_path_task:
  description: >
    Review initial analyses and proposed active postures. Assess signaling
    implications and escalation risks of each proposed active posture.
    Then, provide an overarching recommendation for China's strategic path:
    1. 'Active Posture' (specify which proposed active posture is best),
    2. 'Strategic Ambiguity', or 3. 'Calibrated Delay'. Justify this
    overall recommendation based on escalation control, achieving
    objectives, and international perception management. Output: Concise
    recommendation and risk assessment (max 500 words).
  expected_output: >
    Chosen Strategic Path: [Active Posture: <details of posture> | Strategic Ambiguity | Calibrated Delay].
    This output must be followed by the justification and risk assessment as originally requested.
  agent: StrategicSignalingAssessmentAgent
  context:
    - analyze_event_task
    - assess_economic_tech_impact_task
    - internal_impact_narrative_task
    - develop_active_strategic_postures_task
    - historical_context_task

generate_active_pla_options_task:
  description: >
    IF context.assess_signaling_and_recommend_strategic_path_task.output starts with 'Chosen Strategic Path: Active Posture:':
    Based on the specific active posture chosen ('{context.assess_signaling_and_recommend_strategic_path_task.output}') and
    initial event analysis ('{context.analyze_event_task.output}'), develop 2-3 plausible,
    distinct, concise military/defense response options (max 300 words per option).
    Detail actions (conventional, cyber, space, info warfare), objectives,
    resources, risks, deterrent effects. ELSE, state 'No PLA action for
    non-active posture.'
  expected_output: >
    List of 2-3 military options or 'No PLA action for non-active posture.'
  agent: PLAOptionsStrategistAgent
  context:
    - analyze_event_task
    - assess_economic_tech_impact_task
    - develop_active_strategic_postures_task
    - assess_signaling_and_recommend_strategic_path_task

develop_active_diplomatic_strategy_task:
  description: >
    Based on the chosen strategic path from '{context.assess_signaling_and_recommend_strategic_path_task.output}',
    the initial event analysis from '{context.analyze_event_task.output}', and any PLA options (if applicable) from
    '{context.generate_active_pla_options_task.output}', develop a comprehensive diplomatic strategy.

    The nature of the diplomatic strategy MUST align with the chosen path:

    1.  IF the chosen path is 'Active Posture':
        - Develop a firm diplomatic strategy.
        - Draft a core MFA statement (max 200 words) reflecting this firmness.
        - Identify key international actors to engage or pressure.
        - Outline key talking points for various international fora.
        - Propose diplomatic offensives or de-escalation pathways consistent with any selected PLA actions.

    2.  IF the chosen path is 'Strategic Ambiguity':
        - Develop a diplomatic strategy centered on maintaining ambiguity.
        - Draft a keystone diplomatic statement (max 200 words) that is deliberately vague, non-committal, or deflecting
          (e.g., using phrases like "not aware of the situation," "urge all parties to exercise calm," or "China's position is consistent and clear" without further elaboration).
        - Briefly outline how this posture of ambiguity will be projected and maintained in diplomatic engagements.

    3.  IF the chosen path is 'Calibrated Delay':
        - Develop a diplomatic strategy centered on calibrated delay and information gathering.
        - Draft a keystone holding statement (max 200 words) (e.g., using phrases like "monitoring the situation closely,"
          "call for dialogue," "further information is being gathered").
        - Briefly outline diplomatic actions that support this delay and ongoing assessment.

    The final output must be a concise diplomatic strategy document, including the keystone draft statement (max 200 words)
    and other specified components relevant to the chosen strategic path.
  expected_output: >
    A concise diplomatic strategy document clearly stating the chosen strategic path
    (Active Posture, Strategic Ambiguity, or Calibrated Delay) and including:
    - A keystone draft diplomatic statement (max 200 words) appropriate to that path.
    - For 'Active Posture': Details on actors to engage/pressure, talking points, and offensive/de-escalation ideas.
    - For 'Strategic Ambiguity': Outline of ambiguity maintenance.
    - For 'Calibrated Delay': Outline of diplomatic actions for delay.

    Example for Active Posture:
    "Chosen Path: Active Posture
    Diplomatic Strategy: [Details of actors, talking points, offensive/de-escalation plans].
    Keystone Statement: [Firm statement text, max 200 words]."

    Example for Strategic Ambiguity:
    "Chosen Path: Strategic Ambiguity
    Diplomatic Strategy: [Outline of how ambiguity will be maintained in engagements].
    Keystone Statement: [Vague, non-committal, or deflecting statement text, max 200 words]."

    Example for Calibrated Delay:
    "Chosen Path: Calibrated Delay
    Diplomatic Strategy: [Outline of diplomatic actions to support delay and information gathering].
    Keystone Statement: [Holding statement text, max 200 words]."
  agent: MFADiplomaticStrategistAgent # Ensure this is correctly specified
  context:
    - analyze_event_task
    - assess_economic_tech_impact_task
    - develop_active_strategic_postures_task
    - assess_signaling_and_recommend_strategic_path_task
    - generate_active_pla_options_task
    - historical_context_task
    - internal_impact_narrative_task

ideological_perception_task:
  description: >
    Based on the chosen strategic path from '{context.assess_signaling_and_recommend_strategic_path_task.output}',
    and the MFA diplomatic strategy from '{context.develop_active_diplomatic_strategy_task.output}',
    develop a detailed Ideological Perception Analysis. This analysis must specify-
    1. Core ideological narratives for domestic consumption. 2. Key ideological messages for international audiences
    (differentiating by target region/country if necessary). 3. Guidance for state media outlets.
    4. Themes for unofficial but aligned social media amplification. 5. Potential pre-emptive
    or reactive counter-narrative measures. Actively draw upon the 'Ideological Narrative' and 'Public Opinion'
    sections of 'PRC_GrayZone_Planner.md'.
  expected_output: >
    A concise Ideological Perception Analysis document.
  agent: CCPIdeologicalAnalyst
  context:
    - assess_signaling_and_recommend_strategic_path_task
    - generate_active_pla_options_task
    - develop_active_diplomatic_strategy_task
    - analyze_event_task
    - historical_context_task
    - internal_impact_narrative_task


develop_strategic_communication_plan_task:
  Description:
    Based on the chosen strategic path from '{context.assess_signaling_and_recommend_strategic_path_task.output}',
    any PLA options from '{context.generate_active_pla_options_task.output}',
    and the MFA diplomatic strategy from '{context.develop_active_diplomatic_strategy_task.output}',
    develop a detailed Strategic Communication Plan. This plan must specify-
    1. Core narratives for domestic consumption. 2. Key messages for international audiences
    (differentiating by target region/country if necessary). 3. Guidance for state media outlets.
    4. Themes for unofficial but aligned social media amplification. 5. Potential pre-emptive
    or reactive counter-narrative measures. Actively draw upon the 'Media and Public Perception'
    and 'Denial and Deception' sections of 'PRC_GrayZone_Planner.md'.
  Expected Output:
    A concise Strategic Communication Plan document.
  Agent:
    StrategicNarrativeAndInfluenceAgent
  Context:
    - assess_signaling_and_recommend_strategic_path_task
    - generate_active_pla_options_task
    - develop_active_diplomatic_strategy_task
    - analyze_event_task
    - historical_context_task
    - internal_impact_narrative_task
    - ideological_perception_task



format_final_response_task:
  description: >
    Synthesize the analyses and decisions from previous steps into the final
    public-facing response format, strictly adhering to "XJP Instructions 1.md".
    Consider the chosen strategic path from '{context.assess_signaling_and_recommend_strategic_path_task.output}'.
    If the path is 'Active Posture', incorporate PLA options from '{context.generate_active_pla_options_task.output}'
    and diplomatic strategy from '{context.develop_active_diplomatic_strategy_task.output}'.
    If the path is 'Strategic Ambiguity' or 'Calibrated Delay', the PLA options and active diplomatic strategy might be
    statements of no action or general diplomatic holding statements. Use these to inform your response.
    The primary event analysis is in '{context.analyze_event_task.output}'.
    You MUST consult the "PRC_GrayZone_Planner.md" and "XJP Instructions 1.md"
    knowledge base for style, tone, content, specific phrases (e.g., "good faith emphasis"),
    and common social media narratives.
  expected_output: >
    A string containing the final response formatted exactly as follows:
    China's Actions:
    1. [Action 1, past tense]
    2. [Action 2, past tense, if applicable]
    3. [Action 3, past tense, if applicable]

    Unofficial Social Media Post (Twitter):
    [Tweet content, max 280 chars, incorporating relevant hashtags, emojis, and tone
    reflecting the situation, official messaging, and common Chinese social media narratives,
    including "good faith emphasis" where appropriate.]
  agent: ResponseSynthesizerAgent
  context:
    - analyze_event_task
    - assess_economic_tech_impact_task
    - develop_active_strategic_postures_task
    - assess_signaling_and_recommend_strategic_path_task
    - generate_active_pla_options_task
    - develop_active_diplomatic_strategy_task
    - develop
  output_file: output/final_response.md
