analyze_event_task:
  description: >
    Analyze foreign policy event: {input_event_description}.
    Consider the provided Aggression Level: {aggression_level} and Domain Emphasis: {domain_emphasis}.
    Detail: nature of the event, direct/indirect impact on Chinese core interests,
    initiating entity's likely objectives/red lines, potential escalatory pathways,
    key sensitivities for China. Output: Concise analytical brief (max 500 words).
  expected_output: >
    Concise analytical brief covering event details, impact, objectives,
    escalation, and sensitivities.
  agent: ForeignPolicyEventAnalystAgent

develop_active_strategic_postures_task:
  description: >
    Based on analyses, define 2-3 plausible active strategic response
    postures for China. Justify each by CCP priorities, risk tolerance,
    and desired end-states. Output: Concise document (max 600 words total)
    of active postures with justifications.
  expected_output: >
    Document outlining 2-3 distinct active strategic postures with
    justifications.
  agent: CCPStrategicPolicyAdvisor
  context:
    - analyze_event_task

assess_signaling_and_recommend_strategic_path_task:
  description: >
    Review initial analyses and proposed active postures. Assess signaling
    implications and escalation risks of each proposed active posture.
    Then, provide an overarching recommendation for China's strategic path:
    1. 'Active Posture' (specify which proposed active posture is best),
    2. 'Strategic Ambiguity', or 3. 'Calibrated Delay'. Justify this
    overall recommendation based on escalation control, achieving
    objectives, and international perception management. Output: Concise
    recommendation and risk assessment (max 500 words).
  expected_output: >
    Chosen Strategic Path: [Active Posture: <details of posture> | Strategic Ambiguity | Calibrated Delay].
    This output must be followed by the justification and risk assessment as originally requested.
  agent: StrategicSignalingAssessmentAgent
  context:
    - analyze_event_task
    - develop_active_strategic_postures_task

generate_active_pla_options_task:
  description: >
    IF context.assess_signaling_and_recommend_strategic_path_task.output starts with 'Chosen Strategic Path: Active Posture:':
    Based on the specific active posture chosen ('{context.assess_signaling_and_recommend_strategic_path_task.output}') and
    initial event analysis ('{context.analyze_event_task.output}'), develop 2-3 plausible,
    distinct, concise military/defense response options (max 300 words per option).
    Detail actions (conventional, cyber, space, info warfare), objectives,
    resources, risks, deterrent effects. ELSE, state 'No PLA action for
    non-active posture.'
  expected_output: >
    List of 2-3 military options or 'No PLA action for non-active posture.'
  agent: PLAOptionsStrategistAgent
  context:
    - analyze_event_task
    - assess_signaling_and_recommend_strategic_path_task

develop_active_diplomatic_strategy_task:
  description: >
    IF context.assess_signaling_and_recommend_strategic_path_task.output starts with 'Chosen Strategic Path: Active Posture:':
    Based on chosen posture ('{context.assess_signaling_and_recommend_strategic_path_task.output}'),
    potential/selected PLA actions ('{context.generate_active_pla_options_task.output}'),
    and analysis ('{context.analyze_event_task.output}'), develop a firm diplomatic strategy. Include
    core MFA statement (max 200 words), key talking points, target
    actors/fora, offensive/de-escalation paths. ELSE, state 'No active
    diplomatic strategy for this path.'
  expected_output: >
    Concise active diplomatic strategy & MFA statement, or 'No active
    diplomatic strategy for this path.'
  agent: MFADiplomaticStrategistAgent
  context:
    - analyze_event_task
    - assess_signaling_and_recommend_strategic_path_task
    - generate_active_pla_options_task

format_final_response_task:
  description: >
    Synthesize the analyses and decisions from previous steps into the final
    public-facing response format, strictly adhering to "XJP Instructions 1.md".
    Consider the chosen strategic path from '{context.assess_signaling_and_recommend_strategic_path_task.output}'.
    If the path is 'Active Posture', incorporate PLA options from '{context.generate_active_pla_options_task.output}'
    and diplomatic strategy from '{context.develop_active_diplomatic_strategy_task.output}'.
    If the path is 'Strategic Ambiguity' or 'Calibrated Delay', the PLA options and active diplomatic strategy might be
    statements of no action or general diplomatic holding statements. Use these to inform your response.
    The primary event analysis is in '{context.analyze_event_task.output}'.
    You MUST consult the "Planning Tool for PRC Gray Zone Tactics.md" and "XJP Instructions 1.md"
    knowledge base for style, tone, content, specific phrases (e.g., "good faith emphasis"),
    and common social media narratives.
  expected_output: >
    A string containing the final response formatted exactly as follows:
    China's Actions:
    1. [Action 1, past tense]
    2. [Action 2, past tense, if applicable]
    3. [Action 3, past tense, if applicable]

    Unofficial Social Media Post (Twitter):
    [Tweet content, max 280 chars, incorporating relevant hashtags, emojis, and tone
    reflecting the situation, official messaging, and common Chinese social media narratives,
    including "good faith emphasis" where appropriate.]
  agent: ResponseSynthesizerAgent
  context:
    - analyze_event_task
    - assess_signaling_and_recommend_strategic_path_task
    - generate_active_pla_options_task
    - develop_active_diplomatic_strategy_task
  output_file: output/final_response.md
